feat(demo): reorganize components and dialog refactor
SRGSSR/pillarbox-web pull request #161
Opened 2024-01-05 14:18 UTC by jboix

## Description

Closes #152
Closes #153

This commit focuses on restructuring and enhancing the codebase for improved organization and maintainability. The key aspects of this commit include:

## Changes made

### 1. Folder Layout Reorganization.

The demo folder now follows a revised layout structure:

- **core:** Contains common modules and components, such as the spinner, content-link, dialog, spa router, etc.
- **layout:** Houses pages and major layout elements, including the header, example page, search page, etc.

This restructuring aims to make the demo page more intuitive and modular.

### 2. Refactor `player-dialog` to a web component

The `player-dialog` has been refactored into a web component. This refactor has led to a cleaner separation of concerns, isolating the dialog's styles from the main page.

### 3. Player Query Params Routing Logic

The logic responsible for handling the routing of player query parameters has been relocated to  the `player.js` file. This ensures that the routing-related functionality is centralized within the appropriate file.

2024-01-09 17:18 UTC, amtins commented on demo/src/layout/content/examples/load-media-form-component.js
> +      e.target.classList.classList.remove('active');
An extra `classList` for free?

2024-01-10 13:21 UTC, amtins requested changes
What about something like ?

![image](https://github.com/SRGSSR/pillarbox-web/assets/34163393/6bd59a0b-af79-447c-a96e-85afbc215812)

2024-01-10 15:44 UTC, jboix commented on demo/src/layout/content/examples/load-media-form-component.js
> +      e.target.classList.classList.remove('active');
Done !

2024-01-10 15:59 UTC, amtins approved these changes
LGTM 👌🏽

2024-01-11 08:47 UTC, merged